### ISSUE TITLE
可以用一下里面的 Data 么（（（

### ISSUE THREAD

**Issue by yueyinqiu** [bollwarm/ZHOUYI#1]
想要做点相关的东西，但实在找不到内容又全又好，格式还很规整的原文了（
会放一个链接到这个仓库的（

**Comment by bollwarm** [comment]
可以，DATA就包含在源码里面的__DATA__部分

**Comment by yueyinqiu** [comment]
非常感谢（（

**Comment by yueyinqiu** [comment]
另外，否泰两卦的“标题”好像反了（
![image](https://user-images.githubusercontent.com/18749772/212457781-944dc0cb-e80a-49e1-bbf9-95f0d5bf1893.png)
![image](https://user-images.githubusercontent.com/18749772/212457791-0c5f2590-2e54-4470-b2c6-e351f3e3f28b.png)

**Comment by bollwarm** [comment]
还真是，我改下
